version: "3.8"

services:
  Drugsdb:
      container_name: "Drugsdb"
      image: postgres:14.1-alpine
      restart : always
      environment:
        POSTGRES_PASSWORD: drugsdb
        POSTGRES_USER: drugsdb
        POSTGRES_DB: drugsdb
      ports:
        - "5432:5432"
      networks:
        - custom
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "drugsdb", "-d", "drugsdb", "-h", "localhost", "-p", "5432"]
        interval: 5s
        retries: 5
  Schedulingdb:
      container_name: "Schedulingdb"
      image: postgres:14.1-alpine
      restart : always
      environment:
        POSTGRES_PASSWORD: schedulingdb
        POSTGRES_USER: schedulingdb
        POSTGRES_DB: schedulingdb
      ports:
        - "5430:5432"
      networks:
        - custom
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "schedulingdb", "-d", "schedulingdb", "-h", "localhost", "-p", "5432"]
        interval: 5s
        retries: 5
  Userdb:
    container_name: "Userdb"
    image: postgres:14.1-alpine
    restart : always
    environment:
      POSTGRES_PASSWORD: userdb
      POSTGRES_USER: userdb
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    networks:
      - custom
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "userdb", "-d", "userdb", "-h", "localhost", "-p", "5432"]
      interval: 5s
      retries: 5
  user-service:
    build:
      context: ../Backend/UserService
      dockerfile: ./Dockerfile
    env_file:
    - .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN_ASYNC}
      JWT_SECRET: ${JWT_SECRET}
      RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}
      VERIFICATION_TOKEN_SECRET: ${VERIFICATION_TOKEN_SECRET}
    ports:
      - "5002:5002"
    networks:
      - custom
    depends_on:
      Userdb:
        condition: service_healthy
  scheduling-service:
    build:
      context: ../Backend/SchedulingService
      dockerfile: ./Dockerfile
    env_file:
    - .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN_SCHEDULING}
    ports:
      - "5001:5001"
    networks:
      - custom
    depends_on:
      Schedulingdb:
        condition: service_healthy
  drug-service:
    build:
      context: ../Backend/MedicineService
      dockerfile: ./Dockerfile
    env_file:
    - .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN_DRUG}
    ports:
      - "5000:5000"
    networks:
      - custom
    depends_on:
      Drugsdb:
        condition: service_healthy
networks:
  custom:
    driver: bridge