version: "3.8"

services:
  Userdb:
    container_name: "userdb"
    image: postgres:14.1-alpine
    restart : always
    environment:
      POSTGRES_PASSWORD: userdb
      POSTGRES_USER: userdb
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    networks:
      - custom
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "userdb", "-d", "userdb", "-h", "localhost", "-p", "5432"]
      interval: 5s
      retries: 5
  user-service:
    build:
      context: ../Backend/UserService
      dockerfile: ./Dockerfile
    env_file:
    - .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN_ASYNC}
      JWT_SECRET: ${JWT_SECRET}
      RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}
      VERIFICATION_TOKEN_SECRET: ${VERIFICATION_TOKEN_SECRET}
    ports:
      - "5002:5002"
    networks:
      - custom
    depends_on:
      Userdb:
        condition: service_healthy
networks:
  custom:
    driver: bridge